### ISSUE TITLE
Please support all still-supported Ubuntu releases

### ISSUE THREAD

**Issue by probonopd** [DEAKSoftware/OpenPHT-AppImage#1]
https://github.com/DEAKSoftware/OpenPHT-AppImage/blob/6acd7e5ce44d8c934e05f477d0c4e72cd35e42ae/Recipe/OpenPHT.yml#L4

Please support all still-supported Ubuntu releases by using `trusty`, as trusty is currently the oldest still-supported Ubuntu LTS release. Thank you.

**Comment by DominikDeak** [comment]
Curious, are there problems running a Xenial based `.AppImage`  on Trusty?

**Comment by DominikDeak** [comment]
Got the changes merged. Let me know how it goes.

**Comment by probonopd** [comment]
Thank you. By the way, all that is needed thanks to https://github.com/AppImage/pkg2appimage/blob/master/recipes/OpenPHT.yml is

```
wget https://raw.githubusercontent.com/AppImage/pkg2appimage/master/pkg2appimage
bash -ex pkg2appimage OpenPHT
```
