### ISSUE TITLE
Does not run on all still-supported releases of Ubuntu

### ISSUE THREAD

**Issue by probonopd** [DEAKSoftware/OpenPHT-AppImage#3]
Provide a descriptive summary of the issue.

### Steps to Reproduce

1. Run Ubuntu 14.04 (the oldest currently still-suppported Ubuntu release)
2. Download https://github.com/DEAKSoftware/OpenPHT-AppImage/releases/download/1.8.0.148/OpenPHT-1.8.0.148.glibc2.15-x86_64.AppImage
3. Make executable and run

### Expected Results

Runs on all still-supported releases of Ubuntu.

### Actual Results
Does not run on Ubuntu 14.04:

```
plexhometheater: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /run/firejail/appimage/.appimage-10253/usr/bin/../lib/openpht/plexhometheater)
/run/firejail/appimage/.appimage-10253/usr/bin/../lib/openpht/plexhometheater: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-10253/usr/bin/../lib/openpht/plexhometheater)
```

### Additional Notes

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems

Reference:
https://github.com/AppImage/appimage.github.io/pull/1086

**Comment by DominikDeak** [comment]
In all honesty, I'm not sure the effort involved for this particular fix is going to be worthwhile, considering the end of life date for Ubuntu 14.04 is around [April 2019](https://wiki.ubuntu.com/Releases), which is literally less than 3 months away as of writing this post. Maybe shifting to Xenial support might be a more worthwhile endeavour?

**Comment by probonopd** [comment]
Let's re-visit this in three months then.
