### ISSUE TITLE
VAAPI hardware acceleration not working on Intel NUC

### ISSUE THREAD

**Issue by vnenovd** [DEAKSoftware/OpenPHT-AppImage#4]
The .AppImage version has issues with the hardware acceleration on my Intel NUC.
I am getting an error in the log:  ERROR: VAAPI::CheckSuccess error: unknown libva error

**Comment by vnenovd** [comment]
Thanks. Here is the terminal output:
./OpenPHT-1.8.0.148.glibc2.15-x86_64.AppImage
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1

If I run directly vainfo in terminal:
libva info: VA-API version 1.1.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_1
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.1 (libva 2.1.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Mobile - 2.1.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Simple            : VAEntrypointEncSlice
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD

It seems like the AppImage version as it is built on Trusty, which is using a very old version of the VAAPI library and is not compatible with the Intel driver. See here: https://github.com/intel/media-driver/issues/235
"You are trying to use previous version of libva (API 0.x series) while this driver is compatible with API 1.x."

Here is the debug enabled plexhometheater.log:
http://paste.ubuntu.com/p/s6VH5xv3RR/

**Comment by vnenovd** [comment]
Exactly the same error message:
./OpenPHT-1.8.0.148.glibc2.15-x86_64.AppImage
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so has no function __vaDriverInit_0_32
libva info: va_openDriver() returns -1

Xenial is using libva 1.7.1, Bionic libva 2.1.0, so the package is incompatible.

**Comment by DominikDeak** [comment]
Unfortunately, the official OpenPHT repo does not offer Bionic builds, so i can't do much here at the moment.

That said, I have also converted the Jessie release, you might want to give that a spin.
https://github.com/DEAKSoftware/OpenPHT-AppImage/releases/tag/1.8.0.148
