### ISSUE TITLE
VAAPI problem on Ubuntu bionic 18.04, libva mismatch, again ...

### ISSUE THREAD

**Issue by T-C-R** [DEAKSoftware/OpenPHT-AppImage#5]
Not really an issue with the AppImage published, but the ask to have an updated version for Bionic.

I understand this was already discussed once, and closed already..
But it would really help to have a bionic compatible AppImage of OpenPHT available.
I´m running QNAP HD-Station 4.09, which is based on Ubuntu 18.04, hence I´m exposed to the libva version mismatch causing the VAAPI not to load, so no HW-acceleration.
Thanks to Stefan Balocco´s repository at launchpad we [link to his ppa](https://launchpad.net/~stefanobalocco) have updated binaries available as deb-files, as version 1.9 for OpenPHT. This is the link to the amd64 deb that I would need to be converted [link to the amd64 deb file for OpenPHT 1.9 bionic](https://launchpad.net/~stefanobalocco/+archive/ubuntu/multimedia/+files/openpht_1.9.0.20200314-1~bionic1_amd64.deb)

Actually I´m trying to update your Xenial recipe to a Bionic version, but I struggle to properly understand all of the script.

Could you help in publishing an OpenPHT 1.9 Bionic AppImage based on these deb-files already available? 
Or simply me help me with the recipe Provide a descriptive summary of the issue.

I´m very willing to help with logs etc. if needed, will also post my bionic recipe soon done with it for your review.
Many thanks in advance,

**Comment by DominikDeak** [comment]
Hi, I'm sorry for not responding sooner, I only noticed this issue recently. Thanks for letting me know about the new packages. I've been looking for v1.9 binaries for some time. I'll give this one a shot and how I go.

**Comment by T-C-R** [comment]
No worries. I'm not longer in need for it personally as I meanwhile have switched back to Kodi (Amber) using the official Plex addon to connect to the PMS. This is working quite well, and it provides the possibity to extend the skin with addons for channels etc.
But I believe there is a huge demand for an AppImage of OpenPHT 1.9 anyway.
Just be aware that the binaries will need three libboost libraries to run: libboost-system1.65, libboost-thread1.65 and libboost-timer1.65. These libraries however are available in the official repos. They have not been installed on my HD-Station-like Ubuntu 18.04, which might be different for full fletched distros.
Thanks for your nice tool,
